// src/InventoryTracker.Api/Services/PurchaseOrderService.cs
// Implementation of automated replenishment order generation, PO workflows, and goods receipt intake.
// Connects to: src/InventoryTracker.Api/Data/InventoryDbContext.cs, src/InventoryTracker.Api/Models/PurchaseOrder.cs
// Created: 2026-08-27

using InventoryTracker.Api.Data;
using InventoryTracker.Api.DTOs;
using InventoryTracker.Api.Models;
using Microsoft.EntityFrameworkCore;

namespace InventoryTracker.Api.Services;

/// <summary>
/// Service orchestrating low-stock replenishment analytics, automated PO batch creation, and goods receipt intake.
/// </summary>
public class PurchaseOrderService : IPurchaseOrderService
{
    private readonly InventoryDbContext _context;
    private readonly ILogger<PurchaseOrderService> _logger;

    public PurchaseOrderService(InventoryDbContext context, ILogger<PurchaseOrderService> logger)
    {
        _context = context;
        _logger = logger;
    }

    public async Task<IReadOnlyList<AutoReorderSuggestionDto>> GetAutoReorderSuggestionsAsync(CancellationToken cancellationToken = default)
    {
        var lowStockProducts = await _context.Products
            .AsNoTracking()
            .Include(p => p.PrimarySupplier)
            .Where(p => p.IsActive && p.QuantityInStock <= p.ReorderThreshold)
            .OrderBy(p => p.QuantityInStock)
            .ToListAsync(cancellationToken);

        return lowStockProducts.Select(p => new AutoReorderSuggestionDto
        {
            ProductId = p.Id,
            ProductSku = p.Sku,
            ProductName = p.Name,
            CurrentTotalStock = p.QuantityInStock,
            ReorderThreshold = p.ReorderThreshold,
            RecommendedOrderQuantity = p.ReorderQuantity > 0 ? p.ReorderQuantity : 50,
            UnitCost = p.UnitCost,
            PrimarySupplierId = p.PrimarySupplierId,
            PrimarySupplierName = p.PrimarySupplier?.Name ?? "No Supplier Assigned",
            LeadTimeDays = p.PrimarySupplier?.LeadTimeDays ?? 7
        }).ToList();
    }

    public async Task<AutoGeneratePoResultDto> AutoGeneratePurchaseOrdersAsync(int defaultDestinationWarehouseId, CancellationToken cancellationToken = default)
    {
        var destinationWarehouse = await _context.Warehouses.FindAsync(new object[] { defaultDestinationWarehouseId }, cancellationToken);
        if (destinationWarehouse == null || !destinationWarehouse.IsActive)
        {
            throw new KeyNotFoundException($"Destination warehouse with ID {defaultDestinationWarehouseId} was not found or is inactive.");
        }

        var lowStockProducts = await _context.Products
            .Include(p => p.PrimarySupplier)
            .Where(p => p.IsActive && p.QuantityInStock <= p.ReorderThreshold && p.PrimarySupplierId.HasValue)
            .ToListAsync(cancellationToken);

        if (lowStockProducts.Count == 0)
        {
            return new AutoGeneratePoResultDto
            {
                TotalPurchaseOrdersCreated = 0,
                TotalDistinctItemsReordered = 0,
                TotalUnitsReordered = 0,
                TotalEstimatedCommitment = 0,
                GeneratedPurchaseOrders = new List<PurchaseOrderDto>()
            };
        }

        var createdOrders = new List<PurchaseOrder>();
        var supplierGroups = lowStockProducts.GroupBy(p => p.PrimarySupplierId!.Value);

        foreach (var group in supplierGroups)
        {
            var supplierId = group.Key;
            var supplier = group.First().PrimarySupplier!;
            var orderNumber = $"PO-AUTO-{DateTime.UtcNow:yyyyMMdd}-{Random.Shared.Next(1000, 9999)}";

            var poItems = new List<PurchaseOrderItem>();
            decimal totalCost = 0;

            foreach (var product in group)
            {
                var orderQty = product.ReorderQuantity > 0 ? product.ReorderQuantity : 50;
                poItems.Add(new PurchaseOrderItem
                {
                    ProductId = product.Id,
                    QuantityOrdered = orderQty,
                    QuantityReceived = 0,
                    UnitCost = product.UnitCost
                });
                totalCost += orderQty * product.UnitCost;
            }

            var po = new PurchaseOrder
            {
                OrderNumber = orderNumber,
                SupplierId = supplierId,
                DestinationWarehouseId = defaultDestinationWarehouseId,
                Status = PurchaseOrderStatus.Draft,
                IsAutoGenerated = true,
                TotalEstimatedCost = totalCost,
                ExpectedDeliveryDateUtc = DateTime.UtcNow.AddDays(supplier.LeadTimeDays),
                CreatedBy = "auto_reorder_engine",
                Notes = $"Automated replenishment order triggered for {poItems.Count} low-stock catalog items.",
                CreatedAtUtc = DateTime.UtcNow,
                Items = poItems
            };

            await _context.PurchaseOrders.AddAsync(po, cancellationToken);
            createdOrders.Add(po);
        }

        await _context.SaveChangesAsync(cancellationToken);
        _logger.LogInformation("Auto-generated {Count} replenishment purchase orders.", createdOrders.Count);

        var resultDtos = new List<PurchaseOrderDto>();
        foreach (var order in createdOrders)
        {
            resultDtos.Add(await LoadPurchaseOrderDtoAsync(order.Id, cancellationToken));
        }

        return new AutoGeneratePoResultDto
        {
            TotalPurchaseOrdersCreated = createdOrders.Count,
            TotalDistinctItemsReordered = lowStockProducts.Count,
            TotalUnitsReordered = createdOrders.SelectMany(o => o.Items).Sum(i => i.QuantityOrdered),
            TotalEstimatedCommitment = createdOrders.Sum(o => o.TotalEstimatedCost),
            GeneratedPurchaseOrders = resultDtos
        };
    }

    public async Task<PurchaseOrderDto> CreatePurchaseOrderAsync(CreatePurchaseOrderDto dto, CancellationToken cancellationToken = default)
    {
        var supplier = await _context.Suppliers.FindAsync(new object[] { dto.SupplierId }, cancellationToken);
        if (supplier == null || !supplier.IsActive)
        {
            throw new KeyNotFoundException($"Supplier with ID {dto.SupplierId} was not found or is inactive.");
        }

        var warehouse = await _context.Warehouses.FindAsync(new object[] { dto.DestinationWarehouseId }, cancellationToken);
        if (warehouse == null || !warehouse.IsActive)
        {
            throw new KeyNotFoundException($"Warehouse with ID {dto.DestinationWarehouseId} was not found or is inactive.");
        }

        var orderNumber = $"PO-{DateTime.UtcNow:yyyyMMdd}-{Random.Shared.Next(1000, 9999)}";
        var poItems = new List<PurchaseOrderItem>();
        decimal totalCost = 0;

        foreach (var itemDto in dto.Items)
        {
            var product = await _context.Products.FindAsync(new object[] { itemDto.ProductId }, cancellationToken);
            if (product == null || !product.IsActive)
            {
                throw new KeyNotFoundException($"Product with ID {itemDto.ProductId} was not found or is inactive.");
            }

            var unitCost = itemDto.UnitCostOverride ?? product.UnitCost;
            poItems.Add(new PurchaseOrderItem
            {
                ProductId = product.Id,
                QuantityOrdered = itemDto.Quantity,
                QuantityReceived = 0,
                UnitCost = unitCost
            });
            totalCost += itemDto.Quantity * unitCost;
        }

        var po = new PurchaseOrder
        {
            OrderNumber = orderNumber,
            SupplierId = dto.SupplierId,
            DestinationWarehouseId = dto.DestinationWarehouseId,
            Status = PurchaseOrderStatus.Draft,
            IsAutoGenerated = false,
            TotalEstimatedCost = totalCost,
            ExpectedDeliveryDateUtc = dto.ExpectedDeliveryDateUtc ?? DateTime.UtcNow.AddDays(supplier.LeadTimeDays),
            CreatedBy = string.IsNullOrWhiteSpace(dto.CreatedBy) ? "procurement_agent" : dto.CreatedBy.Trim(),
            Notes = dto.Notes?.Trim(),
            CreatedAtUtc = DateTime.UtcNow,
            Items = poItems
        };

        await _context.PurchaseOrders.AddAsync(po, cancellationToken);
        await _context.SaveChangesAsync(cancellationToken);

        _logger.LogInformation("Purchase order created: {OrderNumber} for {Supplier} ({ItemsCount} lines)",
            po.OrderNumber, supplier.Code, poItems.Count);

        return await LoadPurchaseOrderDtoAsync(po.Id, cancellationToken);
    }

    public async Task<PurchaseOrderDto> SubmitPurchaseOrderAsync(int poId, CancellationToken cancellationToken = default)
    {
        var po = await _context.PurchaseOrders.FindAsync(new object[] { poId }, cancellationToken);
        if (po == null)
        {
            throw new KeyNotFoundException($"Purchase order with ID {poId} was not found.");
        }

        if (po.Status != PurchaseOrderStatus.Draft)
        {
            throw new InvalidOperationException($"Cannot submit purchase order '{po.OrderNumber}' in status '{po.Status}'. Must be Draft.");
        }

        po.Status = PurchaseOrderStatus.Submitted;
        po.SubmittedAtUtc = DateTime.UtcNow;
        await _context.SaveChangesAsync(cancellationToken);

        _logger.LogInformation("Purchase order submitted: {OrderNumber}", po.OrderNumber);
        return await LoadPurchaseOrderDtoAsync(po.Id, cancellationToken);
    }

    public async Task<PurchaseOrderDto> ReceivePurchaseOrderAsync(int poId, ReceivePurchaseOrderDto dto, CancellationToken cancellationToken = default)
    {
        var po = await _context.PurchaseOrders
            .Include(o => o.Items)
            .ThenInclude(i => i.Product)
            .Include(o => o.Supplier)
            .Include(o => o.DestinationWarehouse)
            .FirstOrDefaultAsync(o => o.Id == poId, cancellationToken);

        if (po == null)
        {
            throw new KeyNotFoundException($"Purchase order with ID {poId} was not found.");
        }

        if (po.Status != PurchaseOrderStatus.Submitted && po.Status != PurchaseOrderStatus.PartiallyReceived)
        {
            throw new InvalidOperationException($"Cannot receive goods against purchase order '{po.OrderNumber}' in status '{po.Status}'.");
        }

        foreach (var receiveLine in dto.ReceivedItems)
        {
            var item = po.Items.FirstOrDefault(i => i.Id == receiveLine.PurchaseOrderItemId);
            if (item == null)
            {
                throw new KeyNotFoundException($"Purchase order line item {receiveLine.PurchaseOrderItemId} not found on order {po.OrderNumber}.");
            }

            var product = item.Product!;
            var actualCost = receiveLine.ActualUnitCost ?? item.UnitCost;

            // Recalculate weighted average unit cost on Product
            var currentTotalValuation = product.QuantityInStock * product.UnitCost;
            var incomingValuation = receiveLine.QuantityReceived * actualCost;
            var newTotalUnits = product.QuantityInStock + receiveLine.QuantityReceived;

            if (newTotalUnits > 0)
            {
                product.UnitCost = Math.Round((currentTotalValuation + incomingValuation) / newTotalUnits, 2);
            }

            product.QuantityInStock += receiveLine.QuantityReceived;
            product.UpdatedAtUtc = DateTime.UtcNow;

            item.QuantityReceived += receiveLine.QuantityReceived;

            // Update warehouse stock level
            var warehouseStock = await _context.WarehouseStocks
                .FirstOrDefaultAsync(ws => ws.WarehouseId == po.DestinationWarehouseId && ws.ProductId == item.ProductId, cancellationToken);

            if (warehouseStock == null)
            {
                warehouseStock = new WarehouseStock
                {
                    WarehouseId = po.DestinationWarehouseId,
                    ProductId = item.ProductId,
                    QuantityOnHand = receiveLine.QuantityReceived,
                    QuantityReserved = 0,
                    BinLocation = "UNASSIGNED",
                    UpdatedAtUtc = DateTime.UtcNow
                };
                await _context.WarehouseStocks.AddAsync(warehouseStock, cancellationToken);
            }
            else
            {
                warehouseStock.QuantityOnHand += receiveLine.QuantityReceived;
                warehouseStock.UpdatedAtUtc = DateTime.UtcNow;
            }

            // Create immutable stock intake transaction
            var tx = new InventoryTransaction
            {
                ProductId = item.ProductId,
                Type = TransactionType.StockIn,
                QuantityChange = receiveLine.QuantityReceived,
                QuantityAfter = product.QuantityInStock,
                UnitCost = actualCost,
                Reason = $"PO receiving intake: {po.OrderNumber} from {po.Supplier?.Code}",
                ReferenceNumber = po.OrderNumber,
                PerformedBy = dto.ReceivedBy,
                TimestampUtc = DateTime.UtcNow
            };
            await _context.InventoryTransactions.AddAsync(tx, cancellationToken);
        }

        // Determine if all lines are fully received
        var isFullyFulfilled = po.Items.All(i => i.QuantityReceived >= i.QuantityOrdered);
        po.Status = isFullyFulfilled ? PurchaseOrderStatus.Fulfilled : PurchaseOrderStatus.PartiallyReceived;
        if (isFullyFulfilled)
        {
            po.CompletedAtUtc = DateTime.UtcNow;
        }

        if (!string.IsNullOrWhiteSpace(dto.Notes))
        {
            po.Notes = string.IsNullOrWhiteSpace(po.Notes) ? dto.Notes : $"{po.Notes} | {dto.Notes}";
        }

        await _context.SaveChangesAsync(cancellationToken);
        _logger.LogInformation("Goods received for PO {OrderNumber}: Status={Status}", po.OrderNumber, po.Status);

        return await LoadPurchaseOrderDtoAsync(po.Id, cancellationToken);
    }

    public async Task<PurchaseOrderDto> CancelPurchaseOrderAsync(int poId, string reason, CancellationToken cancellationToken = default)
    {
        var po = await _context.PurchaseOrders.FindAsync(new object[] { poId }, cancellationToken);
        if (po == null)
        {
            throw new KeyNotFoundException($"Purchase order with ID {poId} was not found.");
        }

        if (po.Status == PurchaseOrderStatus.Fulfilled)
        {
            throw new InvalidOperationException($"Cannot cancel fulfilled purchase order '{po.OrderNumber}'.");
        }

        po.Status = PurchaseOrderStatus.Cancelled;
        po.Notes = string.IsNullOrWhiteSpace(po.Notes) ? $"Cancelled: {reason}" : $"{po.Notes} | Cancelled: {reason}";

        await _context.SaveChangesAsync(cancellationToken);
        _logger.LogInformation("Purchase order cancelled: {OrderNumber}", po.OrderNumber);

        return await LoadPurchaseOrderDtoAsync(po.Id, cancellationToken);
    }

    public async Task<PurchaseOrderDto?> GetPurchaseOrderByIdAsync(int id, CancellationToken cancellationToken = default)
    {
        var exists = await _context.PurchaseOrders.AnyAsync(p => p.Id == id, cancellationToken);
        return exists ? await LoadPurchaseOrderDtoAsync(id, cancellationToken) : null;
    }

    public async Task<PagedResult<PurchaseOrderDto>> GetPurchaseOrdersAsync(PurchaseOrderFilterDto filter, CancellationToken cancellationToken = default)
    {
        var query = _context.PurchaseOrders
            .AsNoTracking()
            .Include(p => p.Supplier)
            .Include(p => p.DestinationWarehouse)
            .Include(p => p.Items)
            .ThenInclude(i => i.Product)
            .AsQueryable();

        if (filter.SupplierId.HasValue)
        {
            query = query.Where(p => p.SupplierId == filter.SupplierId.Value);
        }

        if (filter.DestinationWarehouseId.HasValue)
        {
            query = query.Where(p => p.DestinationWarehouseId == filter.DestinationWarehouseId.Value);
        }

        if (filter.Status.HasValue)
        {
            query = query.Where(p => p.Status == filter.Status.Value);
        }

        if (filter.AutoGeneratedOnly.HasValue)
        {
            query = query.Where(p => p.IsAutoGenerated == filter.AutoGeneratedOnly.Value);
        }

        if (!string.IsNullOrWhiteSpace(filter.Search))
        {
            var search = filter.Search.Trim().ToLower();
            query = query.Where(p => p.OrderNumber.ToLower().Contains(search) ||
                                     p.Supplier!.Name.ToLower().Contains(search));
        }

        var totalCount = await query.CountAsync(cancellationToken);
        var page = Math.Max(1, filter.Page);
        var pageSize = Math.Clamp(filter.PageSize, 1, 100);

        var items = await query
            .OrderByDescending(p => p.CreatedAtUtc)
            .Skip((page - 1) * pageSize)
            .Take(pageSize)
            .ToListAsync(cancellationToken);

        var dtos = items.Select(MapToDto).ToList();
        return PagedResult<PurchaseOrderDto>.Create(dtos, totalCount, page, pageSize);
    }

    private async Task<PurchaseOrderDto> LoadPurchaseOrderDtoAsync(int poId, CancellationToken cancellationToken)
    {
        var po = await _context.PurchaseOrders
            .AsNoTracking()
            .Include(p => p.Supplier)
            .Include(p => p.DestinationWarehouse)
            .Include(p => p.Items)
            .ThenInclude(i => i.Product)
            .FirstAsync(p => p.Id == poId, cancellationToken);

        return MapToDto(po);
    }

    private static PurchaseOrderDto MapToDto(PurchaseOrder p) => new()
    {
        Id = p.Id,
        OrderNumber = p.OrderNumber,
        SupplierId = p.SupplierId,
        SupplierCode = p.Supplier?.Code ?? string.Empty,
        SupplierName = p.Supplier?.Name ?? string.Empty,
        DestinationWarehouseId = p.DestinationWarehouseId,
        DestinationWarehouseCode = p.DestinationWarehouse?.Code ?? string.Empty,
        DestinationWarehouseName = p.DestinationWarehouse?.Name ?? string.Empty,
        Status = p.Status,
        IsAutoGenerated = p.IsAutoGenerated,
        TotalEstimatedCost = p.TotalEstimatedCost,
        TotalUnitsOrdered = p.Items.Sum(i => i.QuantityOrdered),
        TotalUnitsReceived = p.Items.Sum(i => i.QuantityReceived),
        ExpectedDeliveryDateUtc = p.ExpectedDeliveryDateUtc,
        CreatedBy = p.CreatedBy,
        Notes = p.Notes,
        CreatedAtUtc = p.CreatedAtUtc,
        SubmittedAtUtc = p.SubmittedAtUtc,
        CompletedAtUtc = p.CompletedAtUtc,
        Items = p.Items.Select(i => new PurchaseOrderItemDto
        {
            Id = i.Id,
            ProductId = i.ProductId,
            ProductSku = i.Product?.Sku ?? string.Empty,
            ProductName = i.Product?.Name ?? string.Empty,
            QuantityOrdered = i.QuantityOrdered,
            QuantityReceived = i.QuantityReceived,
            RemainingQuantity = i.RemainingQuantity,
            UnitCost = i.UnitCost
        }).ToList()
    };
}
