// src/InventoryTracker.Api/DTOs/PurchaseOrderDtos.cs
// Data Transfer Objects for replenishment purchase orders, auto-reorder suggestions, and receiving.
// Connects to: src/InventoryTracker.Api/Models/PurchaseOrder.cs, src/InventoryTracker.Api/Controllers/PurchaseOrdersController.cs
// Created: 2026-08-27

using System.ComponentModel.DataAnnotations;
using InventoryTracker.Api.Models;

namespace InventoryTracker.Api.DTOs;

/// <summary>
/// Data contract returned for purchase order records.
/// </summary>
public class PurchaseOrderDto
{
    public int Id { get; set; }
    public string OrderNumber { get; set; } = string.Empty;
    public int SupplierId { get; set; }
    public string SupplierCode { get; set; } = string.Empty;
    public string SupplierName { get; set; } = string.Empty;
    public int DestinationWarehouseId { get; set; }
    public string DestinationWarehouseCode { get; set; } = string.Empty;
    public string DestinationWarehouseName { get; set; } = string.Empty;
    public PurchaseOrderStatus Status { get; set; }
    public string StatusName => Status.ToString();
    public bool IsAutoGenerated { get; set; }
    public decimal TotalEstimatedCost { get; set; }
    public int TotalUnitsOrdered { get; set; }
    public int TotalUnitsReceived { get; set; }
    public DateTime? ExpectedDeliveryDateUtc { get; set; }
    public string CreatedBy { get; set; } = string.Empty;
    public string? Notes { get; set; }
    public DateTime CreatedAtUtc { get; set; }
    public DateTime? SubmittedAtUtc { get; set; }
    public DateTime? CompletedAtUtc { get; set; }
    public List<PurchaseOrderItemDto> Items { get; set; } = new();
}

/// <summary>
/// Line item data contract within a purchase order.
/// </summary>
public class PurchaseOrderItemDto
{
    public int Id { get; set; }
    public int ProductId { get; set; }
    public string ProductSku { get; set; } = string.Empty;
    public string ProductName { get; set; } = string.Empty;
    public int QuantityOrdered { get; set; }
    public int QuantityReceived { get; set; }
    public int RemainingQuantity { get; set; }
    public decimal UnitCost { get; set; }
    public decimal TotalLineCost => QuantityOrdered * UnitCost;
}

/// <summary>
/// Request payload to manually draft a purchase order.
/// </summary>
public class CreatePurchaseOrderDto
{
    [Required(ErrorMessage = "SupplierId is required.")]
    public int SupplierId { get; set; }

    [Required(ErrorMessage = "DestinationWarehouseId is required.")]
    public int DestinationWarehouseId { get; set; }

    [Required(ErrorMessage = "At least one item is required on the purchase order.")]
    [MinLength(1, ErrorMessage = "At least one item must be included.")]
    public List<CreatePurchaseOrderItemDto> Items { get; set; } = new();

    public string CreatedBy { get; set; } = "procurement_agent";

    [StringLength(500, ErrorMessage = "Notes cannot exceed 500 characters.")]
    public string? Notes { get; set; }

    public DateTime? ExpectedDeliveryDateUtc { get; set; }
}

/// <summary>
/// Line item payload for creating a purchase order.
/// </summary>
public class CreatePurchaseOrderItemDto
{
    [Required(ErrorMessage = "ProductId is required.")]
    public int ProductId { get; set; }

    [Range(1, 1000000, ErrorMessage = "Quantity must be at least 1 unit.")]
    public int Quantity { get; set; }

    [Range(0.00, 1000000.00, ErrorMessage = "UnitCost must be non-negative.")]
    public decimal? UnitCostOverride { get; set; }
}

/// <summary>
/// Automated replenishment recommendation derived from inventory levels vs reorder thresholds.
/// </summary>
public class AutoReorderSuggestionDto
{
    public int ProductId { get; set; }
    public string ProductSku { get; set; } = string.Empty;
    public string ProductName { get; set; } = string.Empty;
    public int CurrentTotalStock { get; set; }
    public int ReorderThreshold { get; set; }
    public int RecommendedOrderQuantity { get; set; }
    public decimal UnitCost { get; set; }
    public decimal EstimatedTotalCost => RecommendedOrderQuantity * UnitCost;
    public int? PrimarySupplierId { get; set; }
    public string? PrimarySupplierName { get; set; }
    public int LeadTimeDays { get; set; }
    public string DeficitSeverity => CurrentTotalStock == 0 ? "CRITICAL_OUT_OF_STOCK" : "LOW_STOCK_WARNING";
}

/// <summary>
/// Result summary after executing auto-generation of purchase orders.
/// </summary>
public class AutoGeneratePoResultDto
{
    public int TotalPurchaseOrdersCreated { get; set; }
    public int TotalDistinctItemsReordered { get; set; }
    public int TotalUnitsReordered { get; set; }
    public decimal TotalEstimatedCommitment { get; set; }
    public List<PurchaseOrderDto> GeneratedPurchaseOrders { get; set; } = new();
}

/// <summary>
/// Request payload to receive goods on an open purchase order.
/// </summary>
public class ReceivePurchaseOrderDto
{
    [Required(ErrorMessage = "At least one item must be received.")]
    [MinLength(1, ErrorMessage = "Must include at least one receiving line.")]
    public List<ReceivePoItemDto> ReceivedItems { get; set; } = new();

    public string ReceivedBy { get; set; } = "warehouse_receiving";

    [StringLength(500, ErrorMessage = "Notes cannot exceed 500 characters.")]
    public string? Notes { get; set; }
}

/// <summary>
/// Individual line item receiving quantity and cost.
/// </summary>
public class ReceivePoItemDto
{
    [Required]
    public int PurchaseOrderItemId { get; set; }

    [Range(1, 1000000, ErrorMessage = "QuantityReceived must be at least 1.")]
    public int QuantityReceived { get; set; }

    public decimal? ActualUnitCost { get; set; }
}

/// <summary>
/// Query filter parameters for purchase order search.
/// </summary>
public class PurchaseOrderFilterDto
{
    public int Page { get; set; } = 1;
    public int PageSize { get; set; } = 20;
    public int? SupplierId { get; set; }
    public int? DestinationWarehouseId { get; set; }
    public PurchaseOrderStatus? Status { get; set; }
    public bool? AutoGeneratedOnly { get; set; }
    public string? Search { get; set; }
}
