// src/InventoryTracker.Api/Models/PurchaseOrder.cs
// Represents a commercial purchase order contract issued to an inventory supplier.
// Connects to: src/InventoryTracker.Api/Models/Supplier.cs, src/InventoryTracker.Api/Models/Warehouse.cs, src/InventoryTracker.Api/Models/PurchaseOrderItem.cs
// Created: 2026-08-27

namespace InventoryTracker.Api.Models;

/// <summary>
/// Domain entity representing a formal replenishment purchase order.
/// </summary>
public class PurchaseOrder
{
    /// <summary>
    /// Unique database primary key identifier.
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Unique business order reference code (e.g. PO-20260827-010).
    /// </summary>
    public string OrderNumber { get; set; } = string.Empty;

    /// <summary>
    /// Foreign key referencing the targeted vendor.
    /// </summary>
    public int SupplierId { get; set; }

    /// <summary>
    /// Navigation reference to the vendor.
    /// </summary>
    public Supplier? Supplier { get; set; }

    /// <summary>
    /// Foreign key referencing the receiving warehouse facility.
    /// </summary>
    public int DestinationWarehouseId { get; set; }

    /// <summary>
    /// Navigation reference to the receiving facility.
    /// </summary>
    public Warehouse? DestinationWarehouse { get; set; }

    /// <summary>
    /// Current procurement processing status.
    /// </summary>
    public PurchaseOrderStatus Status { get; set; } = PurchaseOrderStatus.Draft;

    /// <summary>
    /// Indicates whether the PO was triggered by the automated low-stock reorder engine.
    /// </summary>
    public bool IsAutoGenerated { get; set; } = false;

    /// <summary>
    /// Total estimated cost value of all items in USD.
    /// </summary>
    public decimal TotalEstimatedCost { get; set; }

    /// <summary>
    /// Projected supplier delivery date.
    /// </summary>
    public DateTime? ExpectedDeliveryDateUtc { get; set; }

    /// <summary>
    /// Buyer or automated service creating the order.
    /// </summary>
    public string CreatedBy { get; set; } = "procurement_system";

    /// <summary>
    /// Order notes or vendor instructions.
    /// </summary>
    public string? Notes { get; set; }

    /// <summary>
    /// Timestamp when the order was drafted.
    /// </summary>
    public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Timestamp when the order was officially submitted to vendor.
    /// </summary>
    public DateTime? SubmittedAtUtc { get; set; }

    /// <summary>
    /// Timestamp when final receiving and fulfillment completed.
    /// </summary>
    public DateTime? CompletedAtUtc { get; set; }

    /// <summary>
    /// Collection of item line specifications.
    /// </summary>
    public ICollection<PurchaseOrderItem> Items { get; set; } = new List<PurchaseOrderItem>();
}
